# Generated by Django 5.0.8 on 2024-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
