# Generated by Django 5.1.2 on 2024-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('member', 'Member')], default='librarian', max_length=20),
        ),
    ]
