# Generated by Django 5.0.8 on 2024-10-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
