# Generated by Django 5.0.8 on 2024-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_issuedbook_fine_amount_issuedbook_is_fine_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
